module.exports = Object.assign({},
  require('./CommandController'),
  require('./RoomController'),
  require('./EnemyController'),
  require('./MusicController'),
  require('./UserController'),
  require('./TeamController'),
  require('./MoveController'),
  require('./BattleCharacterController'),
)
